### ISSUE TITLE
Library mess

### ISSUE THREAD

**Issue by C4rl0s79** [psychonic/Playnite-EmuLibrary#12]
Why Addon is putting all games in single library?
It should have different library for every platform. It knows name for platform from config. Then why not use it? 
Sorting by platform is broken if you have GOG laibrary because it includes all plaforms for games that it were released so C64, Amiga.... it is a mess. And if platform is chosen there is no library separation in PC games

**Comment by psychonic** [comment]
I don't have any plans to change this. For the extensions I run, each creates exactly one library, and I do the same here for consistency. It sounds like your main issue is that you have an extension that it putting non-PC platforms into the platform field for PC games.

I'm a little skeptical that it's even the GoG library extension that's doing that for you, as I have 200+ games imported with that, and they all came in as just `PC (Windows)` for platform.
