### ISSUE TITLE
label:question Question about RPCS3.

### ISSUE THREAD

**Issue by Drevis** [psychonic/Playnite-EmuLibrary#3]
Sorry if this is the wrong way to ask a question, I'm not really familiar with github. I've been trying to figure out how to get EmuLibrary working with RPCS3 but keep getting the error "Failed to import games from EmuLibrary. Value cannot be null. Parameter name: source.

I've tried searching the internet with no luck unfortunately, so this is kind of my last ditch effort for answers. Other than that I love the add-on because it pairs so well with my handheld. Thank you for creating this, hope to hear from you soon.

Edit:
I forgot to ask if this emulator was even supported.

**Comment by psychonic** [comment]
The Support section in the README has info on getting support, https://github.com/psychonic/Playnite-EmuLibrary#support
