### ISSUE TITLE
Invalid / Duplicate Mapping IDs

### ISSUE THREAD

**Issue by benspray** [psychonic/Playnite-EmuLibrary#8]
Hi, 

Thanks for this, its working great mostly ;)
I've seen a few issues recently with the mapping id being all zeros on a couple of emulators, when you then try to install a file it errors out as it looks at the wrong source path ie:

 {
      "MappingId": "00000000-0000-0000-0000-000000000000",
      "Enabled": true,
      "EmulatorId": "bffad301-a1e4-43b4-b739-b57f663ba674",
      "EmulatorProfileId": "#custom_0f9aca36-e3be-463d-a333-d1ebf6ad5f30",
      "PlatformId": "sega_saturn",
      "SourcePath": "Z:\\Sega - Saturn",
      "DestinationPath": "C:\\Emulation\\roms\\saturn",
      "RomType": 0
    },
    {
      "MappingId": "00000000-0000-0000-0000-000000000000",
      "Enabled": true,
      "EmulatorId": "06437994-b8f0-4f3d-a7dc-35312c5e8c57",
      "EmulatorProfileId": "#custom_c7109d46-eeb9-4a59-bca2-a91d9754a468",
      "PlatformId": "nintendo_64",
      "SourcePath": "Z:\\Nintendo 64",
      "DestinationPath": "C:\\Emulation\\roms\\n64",
      "RomType": 0
    }

in this example if I go to install a n64 rom it may try to look in the saturn folder instead.
Not sure if its something I've done wrong in the config but I've reset and tried a few times with the same result so thought it was worth raising :)
if I close playnite and manually go into the config file and change the mapping IDs to be unique (before scanning) then reload and scan it seems to work, but once scanned the only way to fix is delete all of the games from playnite then update as above and rescan. 

Thanks

**Comment by psychonic** [comment]
Thanks for the report. I haven't seen that happen before, but I'll see if I can figure out how to reproduce the issue to be able to fix it.

**Comment by psychonic** [comment]
I just released update 3.4.1 in which this case shouldn't be able to happen again. Unfortunately for your case, the mappings and games will need to be removed and readded/rescanned

**Comment by benspray** [comment]
> I just released update 3.4.1 in which this case shouldn't be able to happen again. Unfortunately for your case, the mappings and games will need to be removed and readded/rescanned

Cool thanks :) 👍
